README.md, charts/midaz/Chart.yaml
=> feat: add doc

.github/CODEOWNERS
- [ x ] I have checked for any potential security issues.
=> fix: codeowners groups

charts/midaz/templates/_helpers.tpl, charts/midaz/templates/audit/configmap.yaml, charts/midaz/templates/console/configmap.yaml, charts/midaz/templates/ledger/configmap.yaml, charts/midaz/templates/otel/deployment.yaml, charts/midaz/templates/otel/ingress.yaml, charts/midaz/templates/otel/service.yaml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/values.yaml
- [ x ] I have tested these changes locally.
- [ x ] I have confirmed this code is ready for review.
=> fix: setup otel in template

.github/configs/labeler.yaml, .github/workflows/pr-title.yml
=> fix(pipe): fix pr title workflow

.github/configs/labeler.yaml, .github/workflows/pr-title.yml, README.md, charts/midaz/Chart.yaml, charts/midaz/templates/audit/configmap.yaml, charts/midaz/templates/ledger/configmap.yaml, charts/midaz/templates/ledger/secrets.yml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/templates/transaction/deployment.yaml, charts/midaz/templates/transaction/secrets.yml, charts/midaz/values.yaml
=> feat(values): update midaz version

charts/midaz/templates/audit/configmap.yaml, charts/midaz/templates/audit/deployment.yaml
=> fix(audit): fix audit config

.github/pull_request_template.md, .github/workflows/pr-title.yml, charts/midaz/Chart.yaml
=> feat(dependencies): add new parameters to chart file

.github/workflows/release.yml
- [] I have tested these changes locally.
=> feat(pipe): Add semantic changelog

.github/configs/labeler.yaml, README.md, charts/midaz/templates/_helpers.tpl, charts/midaz/templates/audit/configmap.yaml, charts/midaz/templates/console/configmap.yaml, charts/midaz/templates/grafana/deployment.yaml, charts/midaz/templates/grafana/ingress.yaml, charts/midaz/templates/grafana/service.yaml, charts/midaz/templates/ledger/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/values.yaml
=> fix(dependencies): rename otel to grafana

charts/midaz/templates/console/configmap.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml
=> feat(chart): update version

README.md
=> feat(doc): remove old components

charts/midaz/values.yaml
=> feat(dependencies): disable grafana

README.md
=> feat(doc): add new version

.github/pull_request_template.md, .github/workflows/pr-title.yml, charts/midaz/templates/configmap-casdoor.yaml, charts/midaz/templates/configmap-mariadb.yaml, charts/midaz/templates/configmap-postgres-casdoor.yaml, charts/midaz/templates/console/configmap.yaml, charts/midaz/templates/console/deployment.yaml, charts/midaz/templates/console/hpa.yaml, charts/midaz/templates/console/ingress.yaml, charts/midaz/templates/console/secrets.yml, charts/midaz/templates/console/service.yaml, charts/midaz/templates/console/serviceaccount.yaml, charts/midaz/values.yaml
=> feat(console): add feature flag to console

README.md, charts/midaz/Chart.yaml, charts/midaz/templates/_helpers.tpl, charts/midaz/templates/configmap-casdoor.yaml, charts/midaz/templates/configmap-mariadb.yaml, charts/midaz/templates/configmap-postgres-casdoor.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/onboarding/secrets.yml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/templates/transaction/secrets.yml, charts/midaz/values.yaml
=> refactor(dependencies): replace redis dependency with valkey

.github/configs/labeler.yaml, .github/pull_request_template.md, .github/workflows/pr-title.yml, charts/midaz/templates/_helpers.tpl, charts/midaz/templates/console/configmap.yaml, charts/midaz/templates/console/deployment.yaml, charts/midaz/templates/console/hpa.yaml, charts/midaz/templates/console/ingress.yaml, charts/midaz/templates/console/secrets.yml, charts/midaz/templates/console/service.yaml, charts/midaz/templates/console/serviceaccount.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml
=> chore(chart): add new env var and fixes pipe

.github/configs/labeler.yaml, .github/pull_request_template.md, .github/workflows/pr-title.yml, charts/midaz/templates/_helpers.tpl, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/values.yaml
=> chore(dependencies): rmv old references

.github/configs/labeler.yaml, .github/pull_request_template.md, .github/workflows/pr-title.yml, CHANGELOG.md, charts/midaz/Chart.yaml, charts/midaz/templates/_helpers.tpl, charts/midaz/templates/console/configmap.yaml, charts/midaz/templates/console/deployment.yaml, charts/midaz/templates/console/hpa.yaml, charts/midaz/templates/console/ingress.yaml, charts/midaz/templates/console/secrets.yml, charts/midaz/templates/console/service.yaml, charts/midaz/templates/console/serviceaccount.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/values.yaml
=> chore(dependencies): remove old dependencies and update dependencies

charts/midaz/templates/console/deployment.yaml, charts/midaz/templates/onboarding/deployment.yaml, charts/midaz/templates/transaction/deployment.yaml, charts/midaz/values.yaml
=> feat(chart): add deployment strategy in templates

charts/midaz/templates/console/pdb.yaml, charts/midaz/templates/onboarding/pdb.yaml, charts/midaz/templates/transaction/pdb.yaml, charts/midaz/values.yaml
=> feat(chart): add pdb template

README.md, charts/midaz/Chart.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/values.yaml
=> feat(chart): update app version

CHANGELOG.md, README.md, charts/midaz/Chart.yaml, charts/midaz/templates/console/deployment.yaml, charts/midaz/templates/console/pdb.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/onboarding/deployment.yaml, charts/midaz/templates/onboarding/pdb.yaml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/templates/transaction/deployment.yaml, charts/midaz/templates/transaction/pdb.yaml, charts/midaz/values.yaml
=> feat(chart): update app version 

README.md, charts/midaz/Chart.yaml
=> refactor(chart): rename helm chart

README.md
=> chore(doc): update release version

.github/configs/.releaserc.json, charts/plugin-access-manager/templates/auth/deployment.yaml, charts/plugin-access-manager/values.yaml
=> chore(chart): set stable version

README.md, charts/midaz/README.md, charts/plugin-access-manager/README.md
=> feat(doc): update charts docs

charts/plugin-access-manager/files/init_data.json
=> refactor(chart): auth backend rename default app

README.md, charts/midaz/README.md
=> docs(chart): update midaz chart readme

charts/midaz/Chart.yaml, charts/midaz/templates/console/configmap.yaml, charts/midaz/values.yaml
=> feat(console): update version

README.md, charts/midaz/README.md
=> docs(doc): update versions matrix

README.md, charts/midaz/README.md, charts/plugin-access-manager/README.md
=> feat(doc): update readme

charts/midaz/files/rabbitmq/load_definitions.json
=> refactor(dependencies): remove old component from rabbitmq config file

charts/plugin-fees/Chart.yaml, charts/plugin-fees/README.md
=> chore(chart): add sufixo in chart name

.github/workflows/release.yml
=> chore(pipe): add gpg key to sign bot commits

charts/plugin-access-manager/templates/auth-backend/configmap-auth-db.yaml, charts/plugin-access-manager/templates/auth-backend/configmap-init-config.yaml, charts/plugin-access-manager/templates/auth-backend/deployment.yaml, charts/plugin-access-manager/templates/auth-backend/migrations.yaml, charts/plugin-access-manager/values.yaml
=> feat(dependencies): automates casdoor setup

charts/midaz/templates/console/secrets.yaml, charts/midaz/templates/console/secrets.yml, charts/midaz/values.yaml
=> feat(console): add mongodb environments

charts/midaz/values.yaml
BREAKING CHANGE: Valkey no longer uses StatefulSet. Persistent volume claims from StatefulSet will not be reused automatically.
=> feat(dependencies): Valkey migrate from StatefulSet to Deployment

README.md, charts/midaz/README.md
=> feat(doc): update readme files

charts/plugin-access-manager/values.yaml
=> feat(values): update auth version

charts/midaz/values.yaml
=> fix(console): bump image tag to 2.2.1

charts/midaz/README.md
=> docs(chart): update chart version

charts/plugin-access-manager/README.md, charts/plugin-access-manager/templates/auth/secrets.yaml
=> fix(chart): fix typo in environment variable name

charts/midaz/templates/console/deployment.yaml
=> fix(chart): fix set secret reference to console deployment

.github/workflows/release.yml
=> ci(pipe): add plugin lifecycle management steps

.github/workflows/release.yml
=> fix(pipe): add permissions to workflow

.github/workflows/release.yml, charts/plugin-smart-templates/Chart.yaml
=> fix(pipe): workflow permissions

charts/plugin-smart-templates/Chart.yaml
=> fix(chart): standardize the helm chart name

.github/workflows/release.yml, charts/plugin-smart-templates/Chart.yaml
=> fix: standardize the helm chart name

.github/workflows/pr-title.yml
=> ci(pipe): pr title scopes

.github/configs/labeler.yaml, .github/pull_request_template.md
=> ci(pipe): update labeler and pr template

.github/workflows/pr-sizing.yml
=> ci(pipe): add new permission to action/labeler

charts/plugin-smart-templates/Chart.yaml
=> ci(pipe): standardize the helm chart name

.github/workflows/lint.yml, .github/workflows/release.yml
=> ci(pipe): add matrix to changelog to gpt step 

.github/configs/.releaserc.json, .github/workflows/release.yml
=> ci(pipe): pipe release

charts/plugin-smart-templates/Chart.yaml
=> ci(pipe): trigger release pipeline

.github/workflows/release.yml
=> ci(pipe): add step to publish release in lifecycle management

charts/midaz/Chart.yaml, charts/midaz/README.md, charts/midaz/values.yaml
=> fix(midaz): update app image tag from 2.2.0 to 2.2.1

.github/workflows/release.yml
=> ci(pipe): generate changelog with gpt and publishes closed release only to lifecycle management

.github/workflows/release.yml, charts/midaz/example/README.md, charts/midaz/example/values-template.yaml
=> docs(midaz): add values template example to plugin lifecycle management

.github/configs/.releaserc.json, .github/workflows/release.yml
=> ci(pipe): remove changelog generator from semantic release plugin

charts/midaz/values-template.yaml
=> docs(midaz): create values template example

charts/midaz/values-template.yaml
=> docs(midaz): values template example

.github/configs/.releaserc.json, .github/workflows/pr-title.yml, .github/workflows/release.yml, charts/midaz/CHANGELOG.md, charts/midaz/Chart.yaml, charts/midaz/values-template.yaml
=> docs(midaz): add values example and gpt to generate changelog

README.md, charts/midaz/Chart.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml
=> fix(midaz): update default value of env vars and add Application Version Mapping in README file

charts/plugin-fees/templates/configmap.yaml, charts/plugin-fees/values-template.yaml
=> fix(plugin-fees): update env var default value

README.md
=> feat(doc): update applications version mapping

README.md, charts/plugin-fees/CHANGELOG.md
=> feat(doc): update applications versioin mapping

charts/plugin-smart-templates/vaues-template.yaml
=> feat(plugin-smart-templates): values template file

charts/plugin-access-manager/templates/auth-backend/deployment.yaml, charts/plugin-access-manager/values.yaml
=> feat(plugin-access-manager): app bump version

charts/plugin-access-manager/values-template.yaml
=> feat(plugin-access-manager): add values template file

charts/plugin-access-manager/templates/auth-backend/configmap.yaml
=> fix(plugin-access-manager): remove empty variable

charts/plugin-smart-templates/templates/manager/deployment.yaml, charts/plugin-smart-templates/templates/manager/ingress.yaml, charts/plugin-smart-templates/templates/worker/keda-scaled-job.yaml, charts/plugin-smart-templates/values.yaml
=> feat(plugin-smart-templates): add external secrets support and Ingress Templates

charts/midaz/templates/rabbitmq_external_load_definitions.yaml
=> fix(midaz): fix rabbitmq job to apply default definition

charts/midaz/templates/console/deployment.yaml, charts/midaz/templates/onboarding/deployment.yaml, charts/midaz/templates/transaction/deployment.yaml
=> feat(midaz): add support to external screts

charts/midaz/templates/transaction/deployment.yaml
=> fix(midaz): fix transaction deployment template

charts/plugin-access-manager/templates/auth/configmap.yaml, charts/plugin-access-manager/templates/identity/configmap.yaml, charts/plugin-access-manager/values.yaml
=> feat(plugin-access-manager): add support to extra env vars

charts/plugin-fees/templates/configmap.yaml, charts/plugin-fees/values.yaml
=> feat(plugin-fees): enable extra env vars

charts/midaz/Chart.yaml, charts/midaz/templates/console/nginx_cm_plugins.yaml, charts/midaz/templates/console/nginx_cm_server.yaml, charts/midaz/templates/console/nginx_conf_server.yaml
=> feat(midaz): add nginx to console

charts/otel-collector/Chart.yaml, charts/otel-collector/values.yaml
=> feat(midaz): create internal collector helm chart

charts/midaz/Chart.yaml
=> fix(midaz): Alter version collector

charts/midaz/templates/console/nginx_cm_plugins.yaml, charts/midaz/values.yaml
=> feat(midaz): plugins ui support to console

charts/plugin-smart-templates/templates/manager/secrets.yml, charts/plugin-smart-templates/templates/worker/secrets.yml, charts/plugin-smart-templates/values-template.yaml, charts/plugin-smart-templates/values.yaml
=> chore(plugin-smart-templates): add fee metadata envs and configure redis envs

charts/midaz/templates/console/nginx_conf_server.yaml
=> fix(midaz): nginx server definitions

charts/plugin-smart-templates/templates/worker/secrets.yml
=> chore(plugin-smart-templates): remove unused env vars from worker secret

charts/otel-collector/values.yaml, charts/plugin-access-manager/values.yaml, charts/plugin-smart-templates/values.yaml
=> fix(midaz): Add filter spam atribbute and default values collector

charts/plugin-fees/templates/ui/configmap.yaml, charts/plugin-smart-templates/templates/ui/configmap.yaml
=> chore(plugin-fees): update configmap

charts/plugin-access-manager/templates/auth-backend/migrations.yaml
=> chore(plugin-access-manager): update migration script

charts/midaz/templates/console/configmap.yaml
=> chore(midaz): update console extra env template

charts/midaz/templates/console/nginx_def_server.yaml
=> chore(midaz): update nginx buffers

.github/workflows/release.yml
=> chore(pipe): update release pipeline

charts/plugin-crm/templates/ui/configmap.yaml
=> chore(plugin-crm): remove old env var

charts/midaz/templates/console/nginx_def_server.yaml
=> chore(midaz): update nginx config

charts/plugin-smart-templates/values.yaml
=> chore(plugin-smart-templates): update redis host env var

charts/midaz/Chart.yaml, charts/midaz/docs/UPGRADE-3.0.md, charts/midaz/values.yaml
=> chore(midaz): update app version

README.md
=> docs(midaz): update docs

charts/midaz/templates/console/discovery_service_job.yaml, charts/plugin-access-manager/templates/auth-backend/deployment.yaml, charts/plugin-access-manager/templates/auth-backend/migrations.yaml, charts/plugin-access-manager/values.yaml, charts/plugin-crm/values.yaml, charts/plugin-fees/values.yaml, charts/plugin-smart-templates/values.yaml
=> chore(plugins): bump all plugin versions to 2.0.0 and update Casdoor dependencies

charts/midaz/templates/console/deployment.yaml, charts/midaz/templates/onboarding/deployment.yaml, charts/midaz/templates/transaction/deployment.yaml, charts/midaz/values.yaml, charts/plugin-access-manager/templates/auth-backend/deployment.yaml, charts/plugin-access-manager/templates/auth/deployment.yaml, charts/plugin-access-manager/templates/identity/deployment.yaml, charts/plugin-access-manager/values.yaml, charts/plugin-crm/templates/crm/deployment.yaml, charts/plugin-crm/templates/ui/deployment.yaml, charts/plugin-crm/values.yaml, charts/plugin-fees/templates/fees/deployment.yaml, charts/plugin-fees/templates/ui/deployment.yaml, charts/plugin-fees/values.yaml, charts/plugin-smart-templates/templates/manager/deployment.yaml, charts/plugin-smart-templates/templates/ui/deployment.yaml, charts/plugin-smart-templates/values.yaml
=> chore(plugins): configure revisionHistoryLimit for all deployments in all charts

charts/midaz/Chart.yaml, charts/otel-collector/Chart.yaml, charts/plugin-access-manager/Chart.yaml, charts/plugin-crm/Chart.yaml, charts/plugin-fees/Chart.yaml, charts/plugin-smart-templates/Chart.yaml
=> chore(plugins): docs bump all plugin versions to 2.0.0 

.github/workflows/release.yml
=> ci(pipe): update release workflow

.github/workflows/release.yml, charts/midaz/README.md, charts/otel-collector/Chart.yaml, charts/plugin-access-manager/Chart.yaml, charts/plugin-crm/Chart.yaml, charts/plugin-fees/Chart.yaml, charts/plugin-smart-templates/Chart.yaml
=> chore(plugins): trigger plugins releases

charts/midaz/Chart.yaml, charts/midaz/templates/onboarding/configmap.yaml, charts/midaz/templates/transaction/configmap.yaml, charts/midaz/values.yaml
=> feat(midaz): update midaz app version

charts/plugin-access-manager/templates/auth-backend/deployment.yaml, charts/plugin-access-manager/templates/auth-backend/migrations.yaml, charts/plugin-access-manager/values.yaml
=> chore(plugin-access-manager): allow overriding backend image via values

charts/midaz/Chart.yaml, charts/midaz/values.yaml, charts/otel-collector-lerian/Chart.yaml, charts/otel-collector-lerian/values.yaml, charts/plugin-access-manager/Chart.yaml, charts/plugin-crm/Chart.yaml, charts/plugin-crm/templates/crm/deployment.yaml, charts/plugin-crm/templates/ui/deployment.yaml, charts/plugin-crm/values.yaml, charts/plugin-fees/Chart.yaml, charts/plugin-fees/templates/fees/deployment.yaml, charts/plugin-fees/templates/ui/deployment.yaml, charts/plugin-fees/values.yaml
- [] Plugin Access Manager
- [ x] Plugin Fees
=> chore(midaz): Publish new feature collector

charts/midaz/Chart.yaml
=> chore(midaz): update version collector

charts/midaz/values.yaml
=> fix(midaz): update rabbitmq authentication format to use value

README.md, charts/midaz/Chart.yaml, charts/midaz/docs/UPGRADE-4.0.md, charts/midaz/templates/rabbitmq_load_definitions.yaml, charts/midaz/values-template.yaml, charts/midaz/values.yaml
=> feat(midaz): update midaz default dependencies and bump app version to 3.3.1

charts/plugin-br-pix-direct-jd/templates/plugin-br-pix-direct-jd-qr-code/secrets.yaml
=> fix(plugins): rename PRIVATE_KEY to KEY in qr-code secrets template

charts/plugin-br-pix-direct-jd/templates/plugin-br-pix-direct-jd/secrets.yaml
=> fix(plugins): add missing base64 encoding for JD_SECRET value in secrets template

charts/midaz/templates/console/configmap.yaml, charts/midaz/templates/console/nginx-deployment.yaml
=> fix(midaz): update nginx deployment config with correct service account and simplified configmap names
